In [1]:
# NUMERICAL & DATA MANIPULATION

import pandas as pd
import numpy as np

# DATA VISUALIZATION

import matplotlib.pyplot as plt
import seaborn as sns

### **Data import**

In [2]:
# CREATE A DATA FRAME FROM EACH CSV FILE IN THE DATA FOLDER

customers = pd.read_csv('data/olist_customers_dataset.csv')
order_items = pd.read_csv('data/olist_order_items_dataset.csv')
order_payments = pd.read_csv('data/olist_order_payments_dataset.csv')
orders = pd.read_csv('data/olist_orders_dataset.csv')
products = pd.read_csv('data/olist_products_dataset.csv')

#### **1. EDA**

The content of each single dataset is explored to ensure consistency and spot possible issues.

##### **Customers dataset**

The customers dataset is ready for use. All data formats are appropriate, and no null values are present.

In [3]:
# DISPLAY TOP TWO ROWS IN THE DATAFRAME

customers.head(2)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

In [4]:
# INSPECT DATAFRAME MEDTADATA INCLUDING ENTRIES, COLUMNS, NON-NULL COUNTS, AND DATA TYPES.

customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [5]:
# CHECK IF THE DATAFRAME CONTAINS DUPLICATED DATA.

print(f'The customer dataframe has {customers.duplicated().sum()} duplicated entries.')

The customer dataframe has 0 duplicated entries.

##### **Order items dataset**

The order items dataset is ready for use. All data formats are appropriate, and no null values are present.

In [6]:
# DISPLAY TOP TWO ROWS IN THE DATAFRAME

order_items.head(2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [7]:
# INSPECT DATAFRAME MEDTADATA INCLUDING ENTRIES, COLUMNS, NON-NULL COUNTS, AND DATA TYPES.

order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [8]:
# CHECK IF THE DATAFRAME CONTAINS DUPLICATED DATA.

print(f'The order items dataframe has {order_items.duplicated().sum()} duplicated entries.')

The order items dataframe has 0 duplicated entries.

##### **Order payments dataset**

The order payments dataset is ready for use. All data formats are appropriate, and no null values are present.

In [9]:
# DISPLAY TOP TWO ROWS IN THE DATAFRAME

order_payments.head(2)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

In [10]:
# INSPECT DATAFRAME MEDTADATA INCLUDING ENTRIES, COLUMNS, NON-NULL COUNTS, AND DATA TYPES.

order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [11]:
# CHECK IF THE DATAFRAME CONTAINS DUPLICATED DATA.

print(f'The order payments dataframe has {order_payments.duplicated().sum()} duplicated entries.')

The order payments dataframe has 0 duplicated entries.

##### **Orders dataset**

The orders dataset requires special attention in the following areas:

* **Date and time fields** are incorrectly formatted as objects and need to be converted to proper date or datetime formats.
* **Missing (null) values** are present; a more in-depth exploratory analysis will be conducted to determine the appropriate handling strategy for these records.

In [12]:
# DISPLAY TOP TWO ROWS IN THE DATAFRAME

orders.head(2)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00

In [13]:
# INSPECT DATAFRAME MEDTADATA INCLUDING ENTRIES, COLUMNS, NON-NULL COUNTS, AND DATA TYPES.

orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [14]:
# CHECK IF THE DATAFRAME CONTAINS DUPLICATED DATA.

print(f'The orders dataframe has {orders.duplicated().sum()} duplicated entries.')

The orders dataframe has 0 duplicated entries.

**Handling wrong data types**

In [15]:
# LIST OF COLUMNS THAT SHOULD BE DATETIME BUT CURRENTLY HAVE THE WRONG DATA TYPE.

dates = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']


# APPLY CORRECT DATA TYPE TO THE LISTED COLUMNS

orders[dates] = orders[dates].apply(pd.to_datetime, errors= 'coerce')

In [16]:
# CHECK THE NEW DATA TYPES HAVE BEEN CONVERTED PROPERLY

orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

**Handling null values**

Intuitively, some of the missing values are expected.
For example, orders may not have been approved yet, delivered to the carrier, or received by the customer.
Let’s investigate this in more detail.

In [17]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [18]:
missing_data = orders[orders.isnull().any(axis=1)]
missing_data['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered        23
created           5
approved          2
Name: count, dtype: int64

**'orders_approved_at' column**

Most of the missing data makes sense as they belong to orders that have been canceled or recently created. 
However, around 9% of the total missing values correspond to orders that have already been delivered to the customer

In [24]:
missing_data[missing_data['order_approved_at'].isnull()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [32]:
ff = missing_data[missing_data['order_approved_at'].isnull()][['order_status', 'order_delivered_carrier_date', 'order_delivered_customer_date']]

ff[ff['order_status'] == 'delivered']['order_delivered_customer_date'].isnull().value_counts(normalize=True, dropna= False)

order_delivered_customer_date
False    1.0
Name: proportion, dtype: float64

##### **Products dataset**

The products dataset is ready to be used. Formats make sense and there are no null values.

In [ ]:
# DISPLAY TOP TWO ROWS IN THE DATAFRAME

products.head(2)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

In [ ]:
# INSPECT DATAFRAME MEDTADATA INCLUDING ENTRIES, COLUMNS, NON-NULL COUNTS, AND DATA TYPES.

products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [ ]:
# CHECK IF THE DATAFRAME CONTAINS DUPLICATED DATA.

print(f'The product dataframe has {products.duplicated().sum()} duplicated entries.')

The product dataframe has 0 duplicated entries.